const styles = {
    h2: "capitalize text-white text-3xl font-bold text-center pt-12",
    flexCenterCol: "flex flex-col justify-center items-center",
    flexCenter: "flex justify-center",
    border: "border-t-4 border-[#EF43CF] w-8/12 mt-8",
    mt12: "mt-12",
    title: "text-white text-xl text-center font-bold pt-4",
    p4: "p-4",
    pb4: "pb-4",
    px4: "mx-4",
    shadow: "drop-shadow-[0_20px_20px_rgba(141,125,175,.5)]",
    cursor: "pointer",
    rounded: "rounded",
    bg : "bg-[#472E65]",
    textWhite: "text-white",
    italic:"italic",
    m0:"m-0",
    mt12:"mt-12",
    uppercase: "uppercase",
    mtN4: "-mt-4",
    capitalize: "capitalize",
    leading8:"leading-8",
  };
  
  export default styles;