export const styles = {
  uppercase: "uppercase",
  fontSize: "text-lg",
  fontBold: "font-bold",
  color: "text-white",
  relative: "relative",
  pt6: "pt-6",
  pb6: "pb-6",
  pl4: "pl-4",
  pt2: "pt-2",
  mt2: "mt-4",
  py4: "py-6",
  z0: "z-0",
  z10: "z-10",
  border2: "border-2",
  wFull: "w-full",
  borderAmber400: "border-amber-400",
  flex: "flex",
  justifyCenter: "flex justify-between",
  cursor: "pointer",
  hidden: "hidden",
  h40: "h-[76px]",
  // hoverBlue: "hover:bg-cyan-800  ",
  line: " after:content-[''] after:block after:w-[0px] after:h-[2px] after:rounded-[2px] after:bg-[#EF43CF] after:transtion after:transition-[width] after:duration-200  after:ease-out hover:after:w-full",
  
};

export const stylesLg = {
  hidden: "lg:hidden",
  inline: "lg:inline",
  flex: "lg:flex lg:justify-evenly lg:items-center ",
  py0: "lg:py-0",
  gridCol2: "lg:grid lg:grid-cols-[100px_1fr]",
  mt2: "lg:mt-2",
  gridSelfCenter: "lg:grid lg:justify-self-center",
  wFull: "lg:w-full",
  h16: "lg:h-[66px]",
  p0: "md:p-1",
  
}
