import Head from 'next/head'
import HomePage from './home'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Portfolio de Gorkem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-red-500"><p>lorem hetdf bfhf</p></div>
     <HomePage/>
    </div>
  )
}

export default Home;